
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import org.locationtech.jts.geom
import typing



class DouglasPeuckerSimplifier:
    def __init__(self, geometry: org.locationtech.jts.geom.Geometry): ...
    def getResultGeometry(self) -> org.locationtech.jts.geom.Geometry: ...
    def setDistanceTolerance(self, double: float) -> None: ...
    def setEnsureValid(self, boolean: bool) -> None: ...
    @staticmethod
    def simplify(geometry: org.locationtech.jts.geom.Geometry, double: float) -> org.locationtech.jts.geom.Geometry: ...

class PolygonHullSimplifier:
    def __init__(self, geometry: org.locationtech.jts.geom.Geometry, boolean: bool): ...
    def getResult(self) -> org.locationtech.jts.geom.Geometry: ...
    @staticmethod
    def hull(geometry: org.locationtech.jts.geom.Geometry, boolean: bool, double: float) -> org.locationtech.jts.geom.Geometry: ...
    @staticmethod
    def hullByAreaDelta(geometry: org.locationtech.jts.geom.Geometry, boolean: bool, double: float) -> org.locationtech.jts.geom.Geometry: ...
    def setAreaDeltaRatio(self, double: float) -> None: ...
    def setVertexNumFraction(self, double: float) -> None: ...

class TaggedLineStringSimplifier:
    def __init__(self, lineSegmentIndex: 'LineSegmentIndex', lineSegmentIndex2: 'LineSegmentIndex'): ...
    def setDistanceTolerance(self, double: float) -> None: ...

class TopologyPreservingSimplifier:
    def __init__(self, geometry: org.locationtech.jts.geom.Geometry): ...
    def getResultGeometry(self) -> org.locationtech.jts.geom.Geometry: ...
    def setDistanceTolerance(self, double: float) -> None: ...
    @staticmethod
    def simplify(geometry: org.locationtech.jts.geom.Geometry, double: float) -> org.locationtech.jts.geom.Geometry: ...

class VWSimplifier:
    def __init__(self, geometry: org.locationtech.jts.geom.Geometry): ...
    def getResultGeometry(self) -> org.locationtech.jts.geom.Geometry: ...
    def setDistanceTolerance(self, double: float) -> None: ...
    def setEnsureValid(self, boolean: bool) -> None: ...
    @staticmethod
    def simplify(geometry: org.locationtech.jts.geom.Geometry, double: float) -> org.locationtech.jts.geom.Geometry: ...

class LineSegmentIndex: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.locationtech.jts.simplify")``.

    DouglasPeuckerSimplifier: typing.Type[DouglasPeuckerSimplifier]
    LineSegmentIndex: typing.Type[LineSegmentIndex]
    PolygonHullSimplifier: typing.Type[PolygonHullSimplifier]
    TaggedLineStringSimplifier: typing.Type[TaggedLineStringSimplifier]
    TopologyPreservingSimplifier: typing.Type[TopologyPreservingSimplifier]
    VWSimplifier: typing.Type[VWSimplifier]
