
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import decimal
import java.io
import java.math
import java.util
import javax.xml.namespace
import javax.xml.stream
import jpype
import org.codehaus.stax2
import org.codehaus.stax2.typed
import org.codehaus.stax2.validation
import typing



class DOMWrappingReader(org.codehaus.stax2.XMLStreamReader2, org.codehaus.stax2.AttributeInfo, org.codehaus.stax2.DTDInfo, org.codehaus.stax2.LocationInfo, javax.xml.namespace.NamespaceContext, javax.xml.stream.XMLStreamConstants):
    def close(self) -> None: ...
    def closeCompletely(self) -> None: ...
    def findAttributeIndex(self, string: str, string2: str) -> int: ...
    def getAttributeAs(self, int: int, typedValueDecoder: org.codehaus.stax2.typed.TypedValueDecoder) -> None: ...
    def getAttributeAsArray(self, int: int, typedArrayDecoder: org.codehaus.stax2.typed.TypedArrayDecoder) -> int: ...
    @typing.overload
    def getAttributeAsBinary(self, int: int) -> typing.MutableSequence[int]: ...
    @typing.overload
    def getAttributeAsBinary(self, int: int, base64Variant: org.codehaus.stax2.typed.Base64Variant) -> typing.MutableSequence[int]: ...
    def getAttributeAsBoolean(self, int: int) -> bool: ...
    def getAttributeAsDecimal(self, int: int) -> java.math.BigDecimal: ...
    def getAttributeAsDouble(self, int: int) -> float: ...
    def getAttributeAsDoubleArray(self, int: int) -> typing.MutableSequence[float]: ...
    def getAttributeAsFloat(self, int: int) -> float: ...
    def getAttributeAsFloatArray(self, int: int) -> typing.MutableSequence[float]: ...
    def getAttributeAsInt(self, int: int) -> int: ...
    def getAttributeAsIntArray(self, int: int) -> typing.MutableSequence[int]: ...
    def getAttributeAsInteger(self, int: int) -> java.math.BigInteger: ...
    def getAttributeAsLong(self, int: int) -> int: ...
    def getAttributeAsLongArray(self, int: int) -> typing.MutableSequence[int]: ...
    def getAttributeAsQName(self, int: int) -> javax.xml.namespace.QName: ...
    def getAttributeCount(self) -> int: ...
    def getAttributeIndex(self, string: str, string2: str) -> int: ...
    def getAttributeInfo(self) -> org.codehaus.stax2.AttributeInfo: ...
    def getAttributeLocalName(self, int: int) -> str: ...
    def getAttributeName(self, int: int) -> javax.xml.namespace.QName: ...
    def getAttributeNamespace(self, int: int) -> str: ...
    def getAttributePrefix(self, int: int) -> str: ...
    def getAttributeType(self, int: int) -> str: ...
    @typing.overload
    def getAttributeValue(self, int: int) -> str: ...
    @typing.overload
    def getAttributeValue(self, string: str, string2: str) -> str: ...
    def getCharacterEncodingScheme(self) -> str: ...
    def getCurrentLocation(self) -> org.codehaus.stax2.XMLStreamLocation2: ...
    def getDTDInfo(self) -> org.codehaus.stax2.DTDInfo: ...
    def getDTDInternalSubset(self) -> str: ...
    def getDTDPublicId(self) -> str: ...
    def getDTDRootName(self) -> str: ...
    def getDTDSystemId(self) -> str: ...
    def getDepth(self) -> int: ...
    def getElementAs(self, typedValueDecoder: org.codehaus.stax2.typed.TypedValueDecoder) -> None: ...
    @typing.overload
    def getElementAsBinary(self) -> typing.MutableSequence[int]: ...
    @typing.overload
    def getElementAsBinary(self, base64Variant: org.codehaus.stax2.typed.Base64Variant) -> typing.MutableSequence[int]: ...
    def getElementAsBoolean(self) -> bool: ...
    def getElementAsDecimal(self) -> java.math.BigDecimal: ...
    def getElementAsDouble(self) -> float: ...
    def getElementAsFloat(self) -> float: ...
    def getElementAsInt(self) -> int: ...
    def getElementAsInteger(self) -> java.math.BigInteger: ...
    def getElementAsLong(self) -> int: ...
    def getElementAsQName(self) -> javax.xml.namespace.QName: ...
    def getElementText(self) -> str: ...
    def getEncoding(self) -> str: ...
    def getEndLocation(self) -> org.codehaus.stax2.XMLStreamLocation2: ...
    def getEndingByteOffset(self) -> int: ...
    def getEndingCharOffset(self) -> int: ...
    def getEventType(self) -> int: ...
    def getFeature(self, string: str) -> typing.Any: ...
    def getIdAttributeIndex(self) -> int: ...
    def getLocalName(self) -> str: ...
    def getLocation(self) -> javax.xml.stream.Location: ...
    def getLocationInfo(self) -> org.codehaus.stax2.LocationInfo: ...
    def getName(self) -> javax.xml.namespace.QName: ...
    def getNamespaceContext(self) -> javax.xml.namespace.NamespaceContext: ...
    def getNamespaceCount(self) -> int: ...
    def getNamespacePrefix(self, int: int) -> str: ...
    @typing.overload
    def getNamespaceURI(self) -> str: ...
    @typing.overload
    def getNamespaceURI(self, int: int) -> str: ...
    @typing.overload
    def getNamespaceURI(self, string: str) -> str: ...
    def getNonTransientNamespaceContext(self) -> javax.xml.namespace.NamespaceContext: ...
    def getNotationAttributeIndex(self) -> int: ...
    def getPIData(self) -> str: ...
    def getPITarget(self) -> str: ...
    @typing.overload
    def getPrefix(self) -> str: ...
    @typing.overload
    def getPrefix(self, string: str) -> str: ...
    def getPrefixedName(self) -> str: ...
    def getPrefixes(self, string: str) -> java.util.Iterator[str]: ...
    def getProcessedDTD(self) -> typing.Any: ...
    def getProcessedDTDSchema(self) -> org.codehaus.stax2.validation.DTDValidationSchema: ...
    def getProperty(self, string: str) -> typing.Any: ...
    def getStartLocation(self) -> org.codehaus.stax2.XMLStreamLocation2: ...
    def getStartingByteOffset(self) -> int: ...
    def getStartingCharOffset(self) -> int: ...
    @typing.overload
    def getText(self, writer: java.io.Writer, boolean: bool) -> int: ...
    @typing.overload
    def getText(self) -> str: ...
    @typing.overload
    def getTextCharacters(self) -> typing.MutableSequence[str]: ...
    @typing.overload
    def getTextCharacters(self, int: int, charArray: typing.Union[typing.List[str], jpype.JArray], int2: int, int3: int) -> int: ...
    def getTextLength(self) -> int: ...
    def getTextStart(self) -> int: ...
    def getVersion(self) -> str: ...
    def hasName(self) -> bool: ...
    def hasNext(self) -> bool: ...
    def hasText(self) -> bool: ...
    def isAttributeSpecified(self, int: int) -> bool: ...
    def isCharacters(self) -> bool: ...
    def isEmptyElement(self) -> bool: ...
    def isEndElement(self) -> bool: ...
    def isPropertySupported(self, string: str) -> bool: ...
    def isStandalone(self) -> bool: ...
    def isStartElement(self) -> bool: ...
    def isWhiteSpace(self) -> bool: ...
    def next(self) -> int: ...
    def nextTag(self) -> int: ...
    def readElementAsArray(self, typedArrayDecoder: org.codehaus.stax2.typed.TypedArrayDecoder) -> int: ...
    @typing.overload
    def readElementAsBinary(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int) -> int: ...
    @typing.overload
    def readElementAsBinary(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int, base64Variant: org.codehaus.stax2.typed.Base64Variant) -> int: ...
    def readElementAsDoubleArray(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], int: int, int2: int) -> int: ...
    def readElementAsFloatArray(self, floatArray: typing.Union[typing.List[float], jpype.JArray], int: int, int2: int) -> int: ...
    def readElementAsIntArray(self, intArray: typing.Union[typing.List[int], jpype.JArray], int2: int, int3: int) -> int: ...
    def readElementAsLongArray(self, longArray: typing.Union[typing.List[int], jpype.JArray], int: int, int2: int) -> int: ...
    def require(self, int: int, string: str, string2: str) -> None: ...
    def setFeature(self, string: str, object: typing.Any) -> None: ...
    def setProperty(self, string: str, object: typing.Any) -> bool: ...
    def setValidationProblemHandler(self, validationProblemHandler: org.codehaus.stax2.validation.ValidationProblemHandler) -> org.codehaus.stax2.validation.ValidationProblemHandler: ...
    def skipElement(self) -> None: ...
    def standaloneSet(self) -> bool: ...
    @typing.overload
    def stopValidatingAgainst(self, xMLValidationSchema: org.codehaus.stax2.validation.XMLValidationSchema) -> org.codehaus.stax2.validation.XMLValidator: ...
    @typing.overload
    def stopValidatingAgainst(self, xMLValidator: org.codehaus.stax2.validation.XMLValidator) -> org.codehaus.stax2.validation.XMLValidator: ...
    def validateAgainst(self, xMLValidationSchema: org.codehaus.stax2.validation.XMLValidationSchema) -> org.codehaus.stax2.validation.XMLValidator: ...

class DOMWrappingWriter(org.codehaus.stax2.XMLStreamWriter2):
    def close(self) -> None: ...
    def closeCompletely(self) -> None: ...
    def copyEventFromReader(self, xMLStreamReader2: org.codehaus.stax2.XMLStreamReader2, boolean: bool) -> None: ...
    def flush(self) -> None: ...
    def getEncoding(self) -> str: ...
    def getLocation(self) -> org.codehaus.stax2.XMLStreamLocation2: ...
    def getNamespaceContext(self) -> javax.xml.namespace.NamespaceContext: ...
    def getPrefix(self, string: str) -> str: ...
    def getProperty(self, string: str) -> typing.Any: ...
    def isPropertySupported(self, string: str) -> bool: ...
    def setDefaultNamespace(self, string: str) -> None: ...
    def setNamespaceContext(self, namespaceContext: javax.xml.namespace.NamespaceContext) -> None: ...
    def setPrefix(self, string: str, string2: str) -> None: ...
    def setProperty(self, string: str, object: typing.Any) -> bool: ...
    def setValidationProblemHandler(self, validationProblemHandler: org.codehaus.stax2.validation.ValidationProblemHandler) -> org.codehaus.stax2.validation.ValidationProblemHandler: ...
    @typing.overload
    def stopValidatingAgainst(self, xMLValidationSchema: org.codehaus.stax2.validation.XMLValidationSchema) -> org.codehaus.stax2.validation.XMLValidator: ...
    @typing.overload
    def stopValidatingAgainst(self, xMLValidator: org.codehaus.stax2.validation.XMLValidator) -> org.codehaus.stax2.validation.XMLValidator: ...
    def validateAgainst(self, xMLValidationSchema: org.codehaus.stax2.validation.XMLValidationSchema) -> org.codehaus.stax2.validation.XMLValidator: ...
    @typing.overload
    def writeAttribute(self, string: str, string2: str) -> None: ...
    @typing.overload
    def writeAttribute(self, string: str, string2: str, string3: str) -> None: ...
    @typing.overload
    def writeAttribute(self, string: str, string2: str, string3: str, string4: str) -> None: ...
    @typing.overload
    def writeBinary(self, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int) -> None: ...
    @typing.overload
    def writeBinary(self, base64Variant: org.codehaus.stax2.typed.Base64Variant, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes], int: int, int2: int) -> None: ...
    @typing.overload
    def writeBinaryAttribute(self, string: str, string2: str, string3: str, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    @typing.overload
    def writeBinaryAttribute(self, base64Variant: org.codehaus.stax2.typed.Base64Variant, string: str, string2: str, string3: str, byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> None: ...
    def writeBoolean(self, boolean: bool) -> None: ...
    def writeBooleanAttribute(self, string: str, string2: str, string3: str, boolean: bool) -> None: ...
    @typing.overload
    def writeCData(self, charArray: typing.Union[typing.List[str], jpype.JArray], int: int, int2: int) -> None: ...
    @typing.overload
    def writeCData(self, string: str) -> None: ...
    @typing.overload
    def writeCharacters(self, charArray: typing.Union[typing.List[str], jpype.JArray], int: int, int2: int) -> None: ...
    @typing.overload
    def writeCharacters(self, string: str) -> None: ...
    def writeComment(self, string: str) -> None: ...
    @typing.overload
    def writeDTD(self, string: str, string2: str, string3: str, string4: str) -> None: ...
    @typing.overload
    def writeDTD(self, string: str) -> None: ...
    def writeDecimal(self, bigDecimal: typing.Union[java.math.BigDecimal, decimal.Decimal]) -> None: ...
    def writeDecimalAttribute(self, string: str, string2: str, string3: str, bigDecimal: typing.Union[java.math.BigDecimal, decimal.Decimal]) -> None: ...
    def writeDefaultNamespace(self, string: str) -> None: ...
    def writeDouble(self, double: float) -> None: ...
    def writeDoubleArray(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], int: int, int2: int) -> None: ...
    def writeDoubleArrayAttribute(self, string: str, string2: str, string3: str, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def writeDoubleAttribute(self, string: str, string2: str, string3: str, double: float) -> None: ...
    @typing.overload
    def writeEmptyElement(self, string: str) -> None: ...
    @typing.overload
    def writeEmptyElement(self, string: str, string2: str) -> None: ...
    @typing.overload
    def writeEmptyElement(self, string: str, string2: str, string3: str) -> None: ...
    def writeEndDocument(self) -> None: ...
    def writeEntityRef(self, string: str) -> None: ...
    def writeFloat(self, float: float) -> None: ...
    def writeFloatArray(self, floatArray: typing.Union[typing.List[float], jpype.JArray], int: int, int2: int) -> None: ...
    def writeFloatArrayAttribute(self, string: str, string2: str, string3: str, floatArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def writeFloatAttribute(self, string: str, string2: str, string3: str, float: float) -> None: ...
    def writeFullEndElement(self) -> None: ...
    def writeInt(self, int: int) -> None: ...
    def writeIntArray(self, intArray: typing.Union[typing.List[int], jpype.JArray], int2: int, int3: int) -> None: ...
    def writeIntArrayAttribute(self, string: str, string2: str, string3: str, intArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    def writeIntAttribute(self, string: str, string2: str, string3: str, int: int) -> None: ...
    def writeInteger(self, bigInteger: java.math.BigInteger) -> None: ...
    def writeIntegerAttribute(self, string: str, string2: str, string3: str, bigInteger: java.math.BigInteger) -> None: ...
    def writeLong(self, long: int) -> None: ...
    def writeLongArray(self, longArray: typing.Union[typing.List[int], jpype.JArray], int: int, int2: int) -> None: ...
    def writeLongArrayAttribute(self, string: str, string2: str, string3: str, longArray: typing.Union[typing.List[int], jpype.JArray]) -> None: ...
    def writeLongAttribute(self, string: str, string2: str, string3: str, long: int) -> None: ...
    @typing.overload
    def writeProcessingInstruction(self, string: str) -> None: ...
    @typing.overload
    def writeProcessingInstruction(self, string: str, string2: str) -> None: ...
    def writeQName(self, qName: javax.xml.namespace.QName) -> None: ...
    def writeQNameAttribute(self, string: str, string2: str, string3: str, qName: javax.xml.namespace.QName) -> None: ...
    @typing.overload
    def writeRaw(self, charArray: typing.Union[typing.List[str], jpype.JArray], int: int, int2: int) -> None: ...
    @typing.overload
    def writeRaw(self, string: str) -> None: ...
    @typing.overload
    def writeRaw(self, string: str, int: int, int2: int) -> None: ...
    @typing.overload
    def writeSpace(self, charArray: typing.Union[typing.List[str], jpype.JArray], int: int, int2: int) -> None: ...
    @typing.overload
    def writeSpace(self, string: str) -> None: ...
    @typing.overload
    def writeStartDocument(self) -> None: ...
    @typing.overload
    def writeStartDocument(self, string: str) -> None: ...
    @typing.overload
    def writeStartDocument(self, string: str, string2: str) -> None: ...
    @typing.overload
    def writeStartDocument(self, string: str, string2: str, boolean: bool) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.codehaus.stax2.ri.dom")``.

    DOMWrappingReader: typing.Type[DOMWrappingReader]
    DOMWrappingWriter: typing.Type[DOMWrappingWriter]
