
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import groovy.lang
import jpype
import org.codehaus.groovy.reflection
import org.codehaus.groovy.runtime.callsite
import typing



class ArrayMetaMethod(org.codehaus.groovy.runtime.callsite.CallSiteAwareMetaMethod):
    def __init__(self): ...
    def getModifiers(self) -> int: ...

class ArrayGetAtMetaMethod(ArrayMetaMethod):
    def getName(self) -> str: ...

class ArrayPutAtMetaMethod(ArrayMetaMethod):
    def __init__(self): ...
    def getName(self) -> str: ...
    def getReturnType(self) -> typing.Type: ...

class BooleanArrayGetAtMetaMethod(ArrayGetAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def getReturnType(self) -> typing.Type: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class BooleanArrayPutAtMetaMethod(ArrayPutAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class ByteArrayGetAtMetaMethod(ArrayGetAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def getReturnType(self) -> typing.Type: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class ByteArrayPutAtMetaMethod(ArrayPutAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class CharacterArrayGetAtMetaMethod(ArrayGetAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def getReturnType(self) -> typing.Type: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class CharacterArrayPutAtMetaMethod(ArrayPutAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class DoubleArrayGetAtMetaMethod(ArrayGetAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def getReturnType(self) -> typing.Type: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class DoubleArrayPutAtMetaMethod(ArrayPutAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class FloatArrayGetAtMetaMethod(ArrayGetAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def getReturnType(self) -> typing.Type: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class FloatArrayPutAtMetaMethod(ArrayPutAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class IntegerArrayGetAtMetaMethod(ArrayGetAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def getReturnType(self) -> typing.Type: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class IntegerArrayPutAtMetaMethod(ArrayPutAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class LongArrayGetAtMetaMethod(ArrayGetAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def getReturnType(self) -> typing.Type: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class LongArrayPutAtMetaMethod(ArrayPutAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class ObjectArrayGetAtMetaMethod(ArrayGetAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def getReturnType(self) -> typing.Type: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class ObjectArrayPutAtMetaMethod(ArrayPutAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class ShortArrayGetAtMetaMethod(ArrayGetAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def getReturnType(self) -> typing.Type: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...

class ShortArrayPutAtMetaMethod(ArrayPutAtMetaMethod):
    def __init__(self): ...
    def createPojoCallSite(self, callSite: org.codehaus.groovy.runtime.callsite.CallSite, metaClassImpl: groovy.lang.MetaClassImpl, metaMethod: groovy.lang.MetaMethod, classArray: typing.Union[typing.List[typing.Type], jpype.JArray], object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> org.codehaus.groovy.runtime.callsite.CallSite: ...
    def getDeclaringClass(self) -> org.codehaus.groovy.reflection.CachedClass: ...
    def invoke(self, object: typing.Any, objectArray: typing.Union[typing.List[typing.Any], jpype.JArray]) -> typing.Any: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.codehaus.groovy.runtime.dgmimpl.arrays")``.

    ArrayGetAtMetaMethod: typing.Type[ArrayGetAtMetaMethod]
    ArrayMetaMethod: typing.Type[ArrayMetaMethod]
    ArrayPutAtMetaMethod: typing.Type[ArrayPutAtMetaMethod]
    BooleanArrayGetAtMetaMethod: typing.Type[BooleanArrayGetAtMetaMethod]
    BooleanArrayPutAtMetaMethod: typing.Type[BooleanArrayPutAtMetaMethod]
    ByteArrayGetAtMetaMethod: typing.Type[ByteArrayGetAtMetaMethod]
    ByteArrayPutAtMetaMethod: typing.Type[ByteArrayPutAtMetaMethod]
    CharacterArrayGetAtMetaMethod: typing.Type[CharacterArrayGetAtMetaMethod]
    CharacterArrayPutAtMetaMethod: typing.Type[CharacterArrayPutAtMetaMethod]
    DoubleArrayGetAtMetaMethod: typing.Type[DoubleArrayGetAtMetaMethod]
    DoubleArrayPutAtMetaMethod: typing.Type[DoubleArrayPutAtMetaMethod]
    FloatArrayGetAtMetaMethod: typing.Type[FloatArrayGetAtMetaMethod]
    FloatArrayPutAtMetaMethod: typing.Type[FloatArrayPutAtMetaMethod]
    IntegerArrayGetAtMetaMethod: typing.Type[IntegerArrayGetAtMetaMethod]
    IntegerArrayPutAtMetaMethod: typing.Type[IntegerArrayPutAtMetaMethod]
    LongArrayGetAtMetaMethod: typing.Type[LongArrayGetAtMetaMethod]
    LongArrayPutAtMetaMethod: typing.Type[LongArrayPutAtMetaMethod]
    ObjectArrayGetAtMetaMethod: typing.Type[ObjectArrayGetAtMetaMethod]
    ObjectArrayPutAtMetaMethod: typing.Type[ObjectArrayPutAtMetaMethod]
    ShortArrayGetAtMetaMethod: typing.Type[ShortArrayGetAtMetaMethod]
    ShortArrayPutAtMetaMethod: typing.Type[ShortArrayPutAtMetaMethod]
