
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import groovyjarjarantlr.collections
import java.io
import java.util
import jpype
import org.codehaus.groovy.antlr
import typing



class TraversalHelper(org.codehaus.groovy.antlr.AntlrASTProcessor):
    def __init__(self, visitor: 'Visitor'): ...
    def process(self, aST: groovyjarjarantlr.collections.AST) -> groovyjarjarantlr.collections.AST: ...

class Visitor:
    OPENING_VISIT: typing.ClassVar[int] = ...
    SECOND_VISIT: typing.ClassVar[int] = ...
    SUBSEQUENT_VISIT: typing.ClassVar[int] = ...
    CLOSING_VISIT: typing.ClassVar[int] = ...
    def pop(self) -> org.codehaus.groovy.antlr.GroovySourceAST: ...
    def push(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def visitAbstract(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotation(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotationArrayInit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotationDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotationFieldDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotationMemberValuePair(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotations(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitArrayDeclarator(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBand(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBandAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBigSuffix(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBlock(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBnot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBorAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBsr(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBsrAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBxor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBxorAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCaseGroup(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitClassDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitClosedBlock(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitClosureList(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitClosureOp(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitColon(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitComma(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCompareTo(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCtorCall(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCtorIdent(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDec(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDefault(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDigit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDiv(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDivAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDollar(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDynamicMember(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitElist(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEmptyStat(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEnumConstantDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEnumDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEof(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEqual(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEsc(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitExponent(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitExpr(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitExtendsClause(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitFinal(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitFloatSuffix(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForCondition(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForEachClause(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForInIterable(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForInit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForIterator(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitGe(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitGt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitHexDigit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitIdent(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitImplementsClause(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitImplicitParameters(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitImport(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitInc(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitIndexOp(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitInstanceInit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitInterfaceDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLabeledArg(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLabeledStat(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLand(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLbrack(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLcurly(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLe(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLetter(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitListConstructor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralAs(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralAssert(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralBoolean(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralBreak(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralByte(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralCase(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralCatch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralChar(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralClass(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralContinue(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralDefault(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralDouble(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralElse(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralEnum(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralExtends(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFalse(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFinally(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFloat(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralIf(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralImplements(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralImport(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralIn(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralInstanceof(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralInt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralInterface(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralLong(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralNative(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralNew(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralNull(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralPackage(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralPrivate(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralProtected(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralPublic(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralReturn(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralShort(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralStatic(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralSuper(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralSwitch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralSynchronized(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThis(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThreadsafe(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThrow(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThrows(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralTransient(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralTrue(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralTry(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralVoid(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralVolatile(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralWhile(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLnot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLparen(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMapConstructor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMemberPointer(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMethodCall(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMethodDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMinus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMinusAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMlComment(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMod(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitModAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitModifiers(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMultiCatch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMultiCatchTypes(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNls(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNotEqual(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNullTreeLookahead(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumBigDecimal(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumBigInt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumDouble(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumFloat(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumInt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumLong(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitObjblock(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitOneNl(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitOptionalDot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPackageDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitParameterDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitParameters(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPlus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPlusAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPostDec(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPostInc(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitQuestion(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRangeExclusive(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRangeInclusive(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRbrack(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRcurly(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexFind(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexMatch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexpCtorEnd(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexpLiteral(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexpSymbol(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRparen(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSelectSlot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSemi(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitShComment(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSl(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSlAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSlComment(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSlist(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSpreadArg(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSpreadDot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSpreadMapArg(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSr(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSrAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStar(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStarAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStarStar(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStarStarAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStaticImport(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStaticInit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStrictfp(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringCh(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringConstructor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringCtorEnd(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringCtorMiddle(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringCtorStart(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringLiteral(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringNl(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSuperCtorCall(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTraitDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTripleDot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitType(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeArgument(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeArguments(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeLowerBounds(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeParameter(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeParameters(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeUpperBounds(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypecast(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnaryMinus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnaryPlus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnusedConst(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnusedDo(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnusedGoto(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitVariableDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitVariableParameterDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitVocab(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitWildcardType(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitWs(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...

class CompositeVisitor(Visitor):
    def __init__(self, list: java.util.List): ...
    def pop(self) -> org.codehaus.groovy.antlr.GroovySourceAST: ...
    def push(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def visitAbstract(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotation(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotationArrayInit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotationDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotationFieldDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotationMemberValuePair(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotations(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitArrayDeclarator(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBand(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBandAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBigSuffix(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBlock(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBnot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBorAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBsr(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBsrAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBxor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBxorAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCaseGroup(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitClassDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitClosedBlock(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitClosureList(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitClosureOp(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitColon(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitComma(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCompareTo(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCtorCall(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCtorIdent(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDec(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDefault(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDigit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDiv(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDivAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDollar(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDynamicMember(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitElist(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEmptyStat(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEnumConstantDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEnumDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEof(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEqual(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEsc(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitExponent(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitExpr(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitExtendsClause(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitFinal(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitFloatSuffix(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForCondition(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForEachClause(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForInIterable(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForInit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForIterator(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitGe(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitGt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitHexDigit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitIdent(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitImplementsClause(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitImplicitParameters(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitImport(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitInc(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitIndexOp(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitInstanceInit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitInterfaceDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLabeledArg(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLabeledStat(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLand(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLbrack(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLcurly(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLe(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLetter(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitListConstructor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralAs(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralAssert(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralBoolean(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralBreak(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralByte(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralCase(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralCatch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralChar(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralClass(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralContinue(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralDefault(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralDouble(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralElse(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralEnum(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralExtends(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFalse(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFinally(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFloat(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralIf(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralImplements(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralImport(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralIn(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralInstanceof(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralInt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralInterface(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralLong(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralNative(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralNew(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralNull(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralPackage(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralPrivate(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralProtected(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralPublic(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralReturn(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralShort(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralStatic(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralSuper(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralSwitch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralSynchronized(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThis(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThreadsafe(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThrow(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThrows(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralTransient(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralTrue(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralTry(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralVoid(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralVolatile(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralWhile(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLnot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLparen(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMapConstructor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMemberPointer(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMethodCall(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMethodDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMinus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMinusAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMlComment(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMod(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitModAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitModifiers(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMultiCatch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMultiCatchTypes(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNls(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNotEqual(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNullTreeLookahead(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumBigDecimal(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumBigInt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumDouble(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumFloat(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumInt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumLong(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitObjblock(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitOneNl(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitOptionalDot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPackageDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitParameterDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitParameters(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPlus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPlusAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPostDec(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPostInc(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitQuestion(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRangeExclusive(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRangeInclusive(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRbrack(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRcurly(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexFind(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexMatch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexpCtorEnd(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexpLiteral(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexpSymbol(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRparen(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSelectSlot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSemi(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitShComment(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSl(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSlAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSlComment(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSlist(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSpreadArg(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSpreadDot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSpreadMapArg(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSr(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSrAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStar(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStarAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStarStar(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStarStarAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStaticImport(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStaticInit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStrictfp(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringCh(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringConstructor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringCtorEnd(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringCtorMiddle(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringCtorStart(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringLiteral(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringNl(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSuperCtorCall(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTraitDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTripleDot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitType(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeArgument(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeArguments(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeLowerBounds(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeParameter(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeParameters(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeUpperBounds(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypecast(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnaryMinus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnaryPlus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnusedConst(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnusedDo(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnusedGoto(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitVariableDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitVariableParameterDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitVocab(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitWildcardType(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitWs(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...

class FlatNodeListTraversal(TraversalHelper):
    def __init__(self, visitor: Visitor): ...
    def process(self, aST: groovyjarjarantlr.collections.AST) -> groovyjarjarantlr.collections.AST: ...

class PreOrderTraversal(TraversalHelper):
    def __init__(self, visitor: Visitor): ...
    def accept(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST) -> None: ...

class SourceCodeTraversal(TraversalHelper):
    def __init__(self, visitor: Visitor): ...
    def setUp(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST) -> None: ...

class VisitorAdapter(Visitor):
    def __init__(self): ...
    def pop(self) -> org.codehaus.groovy.antlr.GroovySourceAST: ...
    def push(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def visitAbstract(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotation(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotationArrayInit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotationDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotationFieldDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotationMemberValuePair(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotations(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitArrayDeclarator(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBand(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBandAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBigSuffix(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBlock(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBnot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBorAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBsr(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBsrAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBxor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBxorAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCaseGroup(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitClassDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitClosedBlock(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitClosureList(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitClosureOp(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitColon(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitComma(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCompareTo(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCtorCall(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCtorIdent(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDec(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDefault(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDigit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDiv(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDivAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDollar(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDynamicMember(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitElist(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEmptyStat(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEnumConstantDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEnumDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEof(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEqual(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEsc(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitExponent(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitExpr(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitExtendsClause(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitFinal(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitFloatSuffix(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForCondition(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForEachClause(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForInIterable(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForInit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForIterator(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitGe(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitGt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitHexDigit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitIdent(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitImplementsClause(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitImplicitParameters(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitImport(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitInc(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitIndexOp(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitInstanceInit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitInterfaceDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLabeledArg(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLabeledStat(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLand(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLbrack(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLcurly(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLe(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLetter(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitListConstructor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralAs(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralAssert(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralBoolean(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralBreak(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralByte(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralCase(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralCatch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralChar(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralClass(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralContinue(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralDefault(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralDouble(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralElse(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralEnum(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralExtends(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFalse(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFinally(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFloat(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralIf(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralImplements(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralImport(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralIn(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralInstanceof(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralInt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralInterface(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralLong(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralNative(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralNew(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralNull(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralPackage(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralPrivate(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralProtected(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralPublic(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralReturn(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralShort(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralStatic(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralSuper(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralSwitch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralSynchronized(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThis(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThreadsafe(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThrow(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThrows(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralTransient(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralTrue(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralTry(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralVoid(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralVolatile(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralWhile(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLnot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLparen(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMapConstructor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMemberPointer(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMethodCall(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMethodDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMinus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMinusAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMlComment(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMod(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitModAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitModifiers(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMultiCatch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMultiCatchTypes(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNls(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNotEqual(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNullTreeLookahead(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumBigDecimal(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumBigInt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumDouble(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumFloat(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumInt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumLong(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitObjblock(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitOneNl(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitOptionalDot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPackageDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitParameterDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitParameters(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPlus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPlusAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPostDec(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPostInc(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitQuestion(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRangeExclusive(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRangeInclusive(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRbrack(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRcurly(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexFind(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexMatch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexpCtorEnd(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexpLiteral(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexpSymbol(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRparen(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSelectSlot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSemi(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitShComment(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSl(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSlAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSlComment(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSlist(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSpreadArg(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSpreadDot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSpreadMapArg(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSr(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSrAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStar(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStarAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStarStar(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStarStarAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStaticImport(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStaticInit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStrictfp(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringCh(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringConstructor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringCtorEnd(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringCtorMiddle(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringCtorStart(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringLiteral(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringNl(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSuperCtorCall(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTraitDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTripleDot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitType(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeArgument(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeArguments(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeLowerBounds(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeParameter(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeParameters(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeUpperBounds(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypecast(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnaryMinus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnaryPlus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnusedConst(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnusedDo(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnusedGoto(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitVariableDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitVariableParameterDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitVocab(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitWildcardType(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitWs(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...

class MindMapPrinter(VisitorAdapter):
    @typing.overload
    def __init__(self, printStream: java.io.PrintStream, stringArray: typing.Union[typing.List[str], jpype.JArray]): ...
    @typing.overload
    def __init__(self, printStream: java.io.PrintStream, stringArray: typing.Union[typing.List[str], jpype.JArray], sourceBuffer: org.codehaus.groovy.antlr.SourceBuffer): ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def visitDefault(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...

class NodeAsHTMLPrinter(VisitorAdapter):
    def __init__(self, printStream: java.io.PrintStream, stringArray: typing.Union[typing.List[str], jpype.JArray]): ...
    def pop(self) -> org.codehaus.groovy.antlr.GroovySourceAST: ...
    def push(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def visitDefault(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...

class NodeCollector(VisitorAdapter):
    def __init__(self): ...
    def getNodes(self) -> java.util.List: ...
    def visitDefault(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...

class NodePrinter(VisitorAdapter):
    def __init__(self, printStream: java.io.PrintStream, stringArray: typing.Union[typing.List[str], jpype.JArray]): ...
    def visitDefault(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...

class SourcePrinter(VisitorAdapter):
    @typing.overload
    def __init__(self, printStream: java.io.PrintStream, stringArray: typing.Union[typing.List[str], jpype.JArray]): ...
    @typing.overload
    def __init__(self, printStream: java.io.PrintStream, stringArray: typing.Union[typing.List[str], jpype.JArray], boolean: bool): ...
    def pop(self) -> org.codehaus.groovy.antlr.GroovySourceAST: ...
    def push(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST) -> None: ...
    def visitAbstract(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotation(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotationDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotationFieldDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotationMemberValuePair(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAnnotations(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitArrayDeclarator(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBand(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBandAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBnot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBorAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBsr(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBsrAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBxor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitBxorAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCaseGroup(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitClassDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitClosedBlock(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitClosureList(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCompareTo(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCtorCall(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitCtorIdent(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDec(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDefault(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDiv(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDivAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitDynamicMember(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitElist(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEnumConstantDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEnumDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitEqual(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitExpr(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitExtendsClause(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitFinal(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForCondition(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForInIterable(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForInit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitForIterator(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitGe(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitGt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitIdent(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitImplementsClause(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitImplicitParameters(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitImport(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitInc(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitIndexOp(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitInstanceInit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitInterfaceDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLabeledArg(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLabeledStat(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLand(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLe(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitListConstructor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralAs(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralAssert(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralBoolean(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralBreak(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralByte(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralCase(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralCatch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralChar(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralContinue(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralDefault(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralDouble(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFalse(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFinally(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFloat(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralFor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralIf(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralIn(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralInstanceof(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralInt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralLong(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralNative(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralNew(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralNull(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralPrivate(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralProtected(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralPublic(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralReturn(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralShort(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralStatic(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralSuper(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralSwitch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralSynchronized(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThis(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThreadsafe(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThrow(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralThrows(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralTransient(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralTrue(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralTry(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralVoid(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralVolatile(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLiteralWhile(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLnot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitLt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMapConstructor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMemberPointer(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMethodCall(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMethodDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMinus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMinusAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMod(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitModAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitModifiers(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMultiCatch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitMultiCatchTypes(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNotEqual(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumBigDecimal(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumBigInt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumDouble(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumFloat(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumInt(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitNumLong(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitObjblock(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitOptionalDot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPackageDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitParameterDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitParameters(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPlus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPlusAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPostDec(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitPostInc(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitQuestion(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRangeExclusive(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRangeInclusive(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexFind(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitRegexMatch(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSelectSlot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSl(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSlAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSlist(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSpreadArg(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSpreadDot(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSpreadMapArg(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSr(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSrAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStar(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStarAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStarStar(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStarStarAssign(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStaticImport(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStaticInit(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStrictfp(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringConstructor(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitStringLiteral(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitSuperCtorCall(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTraitDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitType(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeArgument(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeArguments(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeLowerBounds(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeParameter(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeParameters(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypeUpperBounds(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitTypecast(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnaryMinus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitUnaryPlus(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitVariableDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitVariableParameterDef(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...
    def visitWildcardType(self, groovySourceAST: org.codehaus.groovy.antlr.GroovySourceAST, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.codehaus.groovy.antlr.treewalker")``.

    CompositeVisitor: typing.Type[CompositeVisitor]
    FlatNodeListTraversal: typing.Type[FlatNodeListTraversal]
    MindMapPrinter: typing.Type[MindMapPrinter]
    NodeAsHTMLPrinter: typing.Type[NodeAsHTMLPrinter]
    NodeCollector: typing.Type[NodeCollector]
    NodePrinter: typing.Type[NodePrinter]
    PreOrderTraversal: typing.Type[PreOrderTraversal]
    SourceCodeTraversal: typing.Type[SourceCodeTraversal]
    SourcePrinter: typing.Type[SourcePrinter]
    TraversalHelper: typing.Type[TraversalHelper]
    Visitor: typing.Type[Visitor]
    VisitorAdapter: typing.Type[VisitorAdapter]
